import 'package:flutter/material.dart';

ThemeData lightTheme = ThemeData(
  // appBarTheme: const AppBarTheme(
  //   backgroundColor: Color(0xFF5455A9),
  // ),
  // bottomNavigationBarTheme: BottomNavigationBarThemeData(
  //   backgroundColor: Color(0xFFE1DFFF),
  // ),
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF5455A9),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFE1DFFF),
    onPrimaryContainer: Color(0xFF0C0664),
    secondary: Color(0xFF325DA8),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFD8E2FF),
    onSecondaryContainer: Color(0xFF001A42),
    tertiary: Color(0xFF405AA9),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFDCE1FF),
    onTertiaryContainer: Color(0xFF00164D),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFEFBFF),
    onBackground: Color(0xFF001849),
    surface: Color(0xFFFEFBFF),
    onSurface: Color(0xFF001849),
    surfaceVariant: Color(0xBBE4E1EC),
    onSurfaceVariant: Color(0xFF47464F),
    outline: Color(0xFF777680),
    onInverseSurface: Color(0xFFEEF0FF),
    inverseSurface: Color(0xFF002B75),
    inversePrimary: Color(0xFFC1C1FF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF5455A9),
    // outlineVariant: Color(0xFFC8C5D0),
    // scrim: Color(0xFF000000),
  )
);

ThemeData darkTheme = ThemeData(
  // appBarTheme: const AppBarTheme(
  //   backgroundColor: Color(0xFFC1C1FF),
  // ),
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFC1C1FF),
    onPrimary: Color(0xFF242478),
    primaryContainer: Color(0xFF3C3D8F),
    onPrimaryContainer: Color(0xFFE1DFFF),
    secondary: Color(0xFFAEC6FF),
    onSecondary: Color(0xFF002E6A),
    secondaryContainer: Color(0xFF11448F),
    onSecondaryContainer: Color(0xFFD8E2FF),
    tertiary: Color(0xFFB5C4FF),
    onTertiary: Color(0xFF042978),
    tertiaryContainer: Color(0xFF264190),
    onTertiaryContainer: Color(0xFFDCE1FF),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF001849),
    onBackground: Color(0xFFDBE1FF),
    surface: Color(0xFF001849),
    onSurface: Color(0xFFDBE1FF),
    surfaceVariant: Color(0xFF47464F),
    onSurfaceVariant: Color(0xFFC8C5D0),
    outline: Color(0xFF918F9A),
    onInverseSurface: Color(0xFF001849),
    inverseSurface: Color(0xFFDBE1FF),
    inversePrimary: Color(0xFF5455A9),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFC1C1FF),
    // outlineVariant: Color(0xFF47464F),
    // scrim: Color(0xFF000000),
  )
);
